import { getSession } from '@/lib/auth/session'
import { prisma } from '@/lib/db/client'
import MetricsCard from '@/components/dashboard/metrics-card'
import Link from 'next/link'
import { OverviewSuitesTable } from '@/components/dashboard/overview-suites-table'

export default async function DashboardPage() {
  const session = await getSession()
  if (!session?.user?.id) return null

  const [jobs, totalJobs, completedJobs, failedJobs, totalTestResults] = await Promise.all([
    prisma.testJob.findMany({
      where: { repository: { userId: session.user.id } },
      orderBy: { createdAt: 'desc' },
      take: 50,
      include: {
        repository: true,
        testResults: true,
      },
    }),
    prisma.testJob.count({
      where: { repository: { userId: session.user.id } },
    }),
    prisma.testJob.count({
      where: {
        repository: { userId: session.user.id },
        status: 'completed',
      },
    }),
    prisma.testJob.count({
      where: {
        repository: { userId: session.user.id },
        status: 'failed',
      },
    }),
    prisma.testResult.count({
      where: { repository: { userId: session.user.id } },
    }),
  ])

  const successRate =
    totalJobs > 0 ? ((completedJobs / totalJobs) * 100).toFixed(1) : '0'
  const passedLabel = `${completedJobs} passed, ${failedJobs} failed`

  return (
    <div className="relative space-y-8">
      <div
        className="pointer-events-none fixed -top-40 -right-40 h-80 w-80 rounded-full bg-emerald-500/5 blur-3xl dark:bg-emerald-400/5"
        aria-hidden
      />
      <div
        className="pointer-events-none fixed top-1/2 -left-40 h-72 w-72 rounded-full bg-cyan-500/5 blur-3xl dark:bg-cyan-400/5"
        aria-hidden
      />

      {/* Header: title + subtitle + CTA */}
      <div className="relative flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">
            AI-generated test suites
          </h1>
          <p className="mt-2 text-muted-foreground">
            Manage and monitor your AI-generated test suites created by Hiro.
          </p>
        </div>
        <Link
          href="/run-tests"
          className="inline-flex shrink-0 items-center gap-2 rounded-md bg-emerald-500 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-600"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
          </svg>
          Generate New Tests
        </Link>
      </div>

      {/* Search + filters */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative flex-1 min-w-[200px] max-w-md">
          <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
            </svg>
          </span>
          <input
            type="search"
            placeholder="Search test suites..."
            className="w-full rounded-md border border-input bg-background py-2 pl-9 pr-3 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            aria-label="Search test suites"
          />
        </div>
        <input
          type="text"
          placeholder="Filter"
          className="rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring w-32"
          aria-label="Filter"
        />
        <input
          type="text"
          placeholder="Filter"
          className="rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring w-32"
          aria-label="Filter"
        />
      </div>

      {/* KPI cards: AI Test Suites, Total Tests, Success Rate */}
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
        <MetricsCard
          title="AI Test Suites"
          value={totalJobs.toString()}
          description="Auto-generated by Hiro"
          icon="bolt"
        />
        <MetricsCard
          title="Total Tests"
          value={totalTestResults.toString()}
          description="Individual test cases"
          icon="bolt"
        />
        <MetricsCard
          title="Success Rate"
          value={`${successRate}%`}
          description={passedLabel}
          icon="check"
        />
      </div>

      {/* AI-Generated Test Suites table */}
      <div className="rounded-lg border border-border bg-card shadow-sm overflow-hidden">
        <div className="border-b border-border px-4 py-3">
          <h2 className="text-lg font-semibold text-foreground">
            AI-Generated Test Suites
          </h2>
          <p className="text-sm text-muted-foreground">
            Overview of all test suites automatically created by Hiro AI
          </p>
        </div>
        <OverviewSuitesTable jobs={jobs} />
      </div>
    </div>
  )
}
